FROM node:22-alpine

RUN npm install -g pnpm@10.6.3

WORKDIR /app

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY apps/api-server/package.json ./apps/api-server/
COPY packages/core-domain/package.json ./packages/core-domain/
COPY packages/data-access/package.json ./packages/data-access/
COPY packages/config/package.json ./packages/config/

RUN pnpm install

COPY packages/core-domain ./packages/core-domain
COPY packages/data-access ./packages/data-access
COPY apps/api-server ./apps/api-server
COPY packages/config ./packages/config/

RUN pnpm turbo run build --filter="./packages/*"

RUN pnpm install

EXPOSE 3000

WORKDIR /app

CMD ["pnpm", "--filter", "@agroshield/api-server", "dev"]
