// Re-export contracts with @ts-ignore to bypass TypeScript checking of autogenerated files
export * from './sway-programs-api/contracts';

// Import and export contract IDs dynamically
import contractIds from './sway-programs-api/contract-ids.json';

export const CONTRACT_IDS = contractIds;
