# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: indexer-test
ecosystem: fuel
networks:
- id: 0
  start_block: 0
  contracts:
  - name: InsuranceManager
    address:
    - 0xd395f43d6d50fb616e70640bbfebea221d39b2a15280d6dab69cd4552c6bfa28
    abi_file_path: abis/insurancemanager-abi.json
    handler: src/EventHandlers.ts
    events:
    - name: ApproveClaimEvent
      logId: '12097520186714049702'
    - name: ExpirePolicyEvent
      logId: '17592643628849736535'
    - name: RegisterPolicyEvent
      logId: '16702917729177687366'
    - name: RejectClaimEvent
      logId: '8420981007029399393'
    - name: RequestClaimEvent
      logId: '8664469497107667899'